export const authConstants = {
    USER_LOGIN : 'USER_LOGIN',
    USER_LOGOUT : 'USER_LOGOUT',
    UPDATE_USER_AVATAR : 'UPDATE_USER_AVATAR'
}

export const userConstants = {
    GET_REALTIME_USERS : 'GET_REALTIME_USERS',
    UPDATE_MESSAGE : 'UPDATE_MESSAGE',
    GET_REALTIME_MESSAGE : 'GET_REALTIME_MESSAGE',
    SET_SEEN_MESSAGE : 'SET_SEEN_MESSAGE',
    GET_LOADMORE_MESSAGE : 'GET_LOADMORE_MESSAGE',

}
export const postConstants = {
    PUSH_POST : 'PUSH_POST',
    GET_REALTIME_POSTS : 'GET_REALTIME_POSTS',
    GET_POST_BY_KEY:'GET_POST_BY_KEY',
    CLEAR_POST_ITEM :'CLEAR_POST_ITEM',
    PUSH_COMMENT : 'PUSH_COMMENT'
}

export const interactionConstants = {
    GET_REALTIME_INTERACTIONS : 'GET_REALTIME_INTERACTIONS',
    UPDATE_LIKE : 'UPDATE_LIKES',
}