export const authConstants = {
    USER_LOGIN : 'USER_LOGIN',
    USER_LOGOUT : 'USER_LOGOUT'
}

export const userConstants = {
    GET_REALTIME_USERS : 'GET_REALTIME_USERS',
    UPDATE_MESSAGE : 'UPDATE_MESSAGE',
    GET_REALTIME_MESSAGE : 'GET_REALTIME_MESSAGE',
    SET_SEEN_MESSAGE : 'SET_SEEN_MESSAGE',
    GET_LOADMORE_MESSAGE : 'GET_LOADMORE_MESSAGE',
}
